# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42bdcd6daa6fdbf217268f4b57ac6119aed985e1802bfdb73d30c5be15f4494006787e8452b08a37a386ace188a6f6fa1f1ebeb7cbe98694788e73961f168d4d

test:
  secret_key_base: 8122791cea00d1e5d4608c8e5d251fe13a62dd98b440fbfa87d0ca69e1ed517b4c970eb6c51637b83566ff54bfc1d63c38d8dd844c583966083f93af2359e8e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
